#include "ignore.h"
#include <stdio.h>
#include <string.h>

#define GITIGNORE_FILE ".gitignore"

static int file_exists(const char *path) {
    FILE *fp = fopen(path, "r");
    if (fp) {
        fclose(fp);
        return 1;
    }
    return 0;
}

void ignore_init(void) {
    if (file_exists(GITIGNORE_FILE)) {
        return;
    }

    FILE *fp = fopen(GITIGNORE_FILE, "w");
    if (!fp) return;

    fprintf(fp,
        "# Generated by git_auto\n"
        ".gitauto.conf\n"
        "*.log\n"
        "*.tmp\n"
    );

    fclose(fp);
}

void ignore_ensure_entry(const char *entry) {
    FILE *fp = fopen(GITIGNORE_FILE, "r");
    if (!fp) {
        /* .gitignore 不存在，直接初始化 */
        ignore_init();
        return;
    }

    char line[256];
    while (fgets(line, sizeof(line), fp)) {
        /* 去掉换行 */
        line[strcspn(line, "\r\n")] = 0;

        if (strcmp(line, entry) == 0) {
            fclose(fp);
            return; /* 已存在 */
        }
    }
    fclose(fp);

    /* 追加写入 */
    fp = fopen(GITIGNORE_FILE, "a");
    if (!fp) return;

    fprintf(fp, "%s\n", entry);
    fclose(fp);
}
